/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KarriereRouteImport } from './routes/karriere'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsletterBestaetigenRouteImport } from './routes/newsletter.bestaetigen'
import { Route as NewsletterAbmeldenRouteImport } from './routes/newsletter.abmelden'
import { Route as FahrzeugSlugRouteImport } from './routes/fahrzeug.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereRoute = KarriereRouteImport.update({
  id: '/karriere',
  path: '/karriere',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterBestaetigenRoute = NewsletterBestaetigenRouteImport.update({
  id: '/newsletter/bestaetigen',
  path: '/newsletter/bestaetigen',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterAbmeldenRoute = NewsletterAbmeldenRouteImport.update({
  id: '/newsletter/abmelden',
  path: '/newsletter/abmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const FahrzeugSlugRoute = FahrzeugSlugRouteImport.update({
  id: '/fahrzeug/$slug',
  path: '/fahrzeug/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/fahrzeug/$slug': typeof FahrzeugSlugRoute
  '/newsletter/abmelden': typeof NewsletterAbmeldenRoute
  '/newsletter/bestaetigen': typeof NewsletterBestaetigenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/fahrzeug/$slug': typeof FahrzeugSlugRoute
  '/newsletter/abmelden': typeof NewsletterAbmeldenRoute
  '/newsletter/bestaetigen': typeof NewsletterBestaetigenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/karriere': typeof KarriereRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/fahrzeug/$slug': typeof FahrzeugSlugRoute
  '/newsletter/abmelden': typeof NewsletterAbmeldenRoute
  '/newsletter/bestaetigen': typeof NewsletterBestaetigenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/karriere'
    | '/sitemap.xml'
    | '/fahrzeug/$slug'
    | '/newsletter/abmelden'
    | '/newsletter/bestaetigen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/karriere'
    | '/sitemap.xml'
    | '/fahrzeug/$slug'
    | '/newsletter/abmelden'
    | '/newsletter/bestaetigen'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/karriere'
    | '/sitemap.xml'
    | '/fahrzeug/$slug'
    | '/newsletter/abmelden'
    | '/newsletter/bestaetigen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KarriereRoute: typeof KarriereRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FahrzeugSlugRoute: typeof FahrzeugSlugRoute
  NewsletterAbmeldenRoute: typeof NewsletterAbmeldenRoute
  NewsletterBestaetigenRoute: typeof NewsletterBestaetigenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere': {
      id: '/karriere'
      path: '/karriere'
      fullPath: '/karriere'
      preLoaderRoute: typeof KarriereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/bestaetigen': {
      id: '/newsletter/bestaetigen'
      path: '/newsletter/bestaetigen'
      fullPath: '/newsletter/bestaetigen'
      preLoaderRoute: typeof NewsletterBestaetigenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/abmelden': {
      id: '/newsletter/abmelden'
      path: '/newsletter/abmelden'
      fullPath: '/newsletter/abmelden'
      preLoaderRoute: typeof NewsletterAbmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fahrzeug/$slug': {
      id: '/fahrzeug/$slug'
      path: '/fahrzeug/$slug'
      fullPath: '/fahrzeug/$slug'
      preLoaderRoute: typeof FahrzeugSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KarriereRoute: KarriereRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FahrzeugSlugRoute: FahrzeugSlugRoute,
  NewsletterAbmeldenRoute: NewsletterAbmeldenRoute,
  NewsletterBestaetigenRoute: NewsletterBestaetigenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
